name: Feature Request
description: Suggest a new feature or enhancement for MeshCore.Net.SDK
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible about what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.

  - type: textarea
    id: example
    attributes:
      label: Code Example
      description: If applicable, show how you'd like to use this feature
      render: csharp
      placeholder: |
        using MeshCore.Net.SDK;
        
        // Example of how the new feature would work
        var client = new MeshCodeClient("COM5");
        await client.NewFeatureAsync();

  - type: checkboxes
    id: impact
    attributes:
      label: Feature Impact
      description: What areas would this feature affect?
      options:
        - label: Core SDK functionality
        - label: USB transport layer
        - label: Protocol implementation
        - label: Device discovery
        - label: Error handling
        - label: Documentation
        - label: Examples/demos
        - label: Performance
        - label: Cross-platform compatibility

  - type: input
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      placeholder: e.g., High, Medium, Low

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.